[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.17", features = ["full"]}
pushover = "0.4.0"
chrono = "0.4.19"
rand = "0.8.5"